name: towermarket
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.7.0
  equatable: ^2.0.3
  cloud_firestore: ^4.4.3
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  cached_network_image: ^3.2.1
  shimmer: ^2.0.0
  firebase_auth: ^4.2.10
  flutter_bloc: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.1.11

flutter:
  generate: true
  uses-material-design: true
  fonts: 
    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
          weight: 400

