name: towermarket
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.17.1
  equatable: ^2.0.3
  cloud_firestore: ^3.1.17
  # path_provider: ^2.0.11
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  cached_network_image: ^3.2.1
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.1.11

flutter:
  uses-material-design: true
  fonts: 
    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
          weight: 400

