name: towermarket
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  open_file: ^3.2.1
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  cloud_firestore: ^3.1.17
  image_picker: ^0.8.5+3
  firebase_storage: ^10.2.17
  path_provider: ^2.0.11
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  pdf: ^3.8.1
  printing: ^5.9.1
  cached_network_image: ^3.2.1
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.1.11


flutter:

  uses-material-design: true
  assets:
    - assets/

  fonts: 
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf
          weight: 400

