// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOx6U95tVKzP8nbZMaJPyiEJKf37RdfU8',
    appId: '1:812275202272:web:7519acb90c8dd9169cb885',
    messagingSenderId: '812275202272',
    projectId: 'towermarket-77c5a',
    authDomain: 'towermarket-77c5a.firebaseapp.com',
    storageBucket: 'towermarket-77c5a.appspot.com',
    measurementId: 'G-C6GNTCWXZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCndrCfzhMdCFIDDkrroKlB8Zk6WoulqPo',
    appId: '1:812275202272:android:90b262e1db5a1c379cb885',
    messagingSenderId: '812275202272',
    projectId: 'towermarket-77c5a',
    storageBucket: 'towermarket-77c5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmA05sYgH1dU3sBZ2GjtNdkA_dfitQDN0',
    appId: '1:812275202272:ios:aa7f7b31d8eb40c69cb885',
    messagingSenderId: '812275202272',
    projectId: 'towermarket-77c5a',
    storageBucket: 'towermarket-77c5a.appspot.com',
    iosClientId: '812275202272-6ile6k3imivcfskkpq6h9rgl6n1g0f7r.apps.googleusercontent.com',
    iosBundleId: 'com.example.towermarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmA05sYgH1dU3sBZ2GjtNdkA_dfitQDN0',
    appId: '1:812275202272:ios:aa7f7b31d8eb40c69cb885',
    messagingSenderId: '812275202272',
    projectId: 'towermarket-77c5a',
    storageBucket: 'towermarket-77c5a.appspot.com',
    iosClientId: '812275202272-6ile6k3imivcfskkpq6h9rgl6n1g0f7r.apps.googleusercontent.com',
    iosBundleId: 'com.example.towermarket',
  );
}
